<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Back to products_inventory_details_img</name>
   <tag></tag>
   <elementGuidId>6a58f58b-e9b2-4a7b-ab00-b1299152798e</elementGuidId>
   <imagePath>https://www.saucedemo.com/static/media/bolt-shirt-1200x1500.c2599ac5f0a35ed5931e.jpg</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inventory_details_img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>https://www.saucedemo.com/static/media/bolt-shirt-1200x1500.c2599ac5f0a35ed5931e.jpg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;item-sauce-labs-fleece-jacket-img&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9d1c6932-9da5-48c5-b0d6-3bb72e78284d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Fleece Jacket</value>
      <webElementGuid>b4dfa6b4-0903-4c6c-91ef-d276ce4f2875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_details_img</value>
      <webElementGuid>8f80517f-ee85-4171-85b8-4adf32ec65d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/sauce-pullover-1200x1500.51d7ffaf301e698772c8.jpg</value>
      <webElementGuid>c2ffca7e-0d2e-4005-b889-314b6f9ec01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>item-sauce-labs-fleece-jacket-img</value>
      <webElementGuid>aa252bcd-1fba-4275-9eb8-d29b9fc0a561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventory_item_container&quot;)/div[@class=&quot;inventory_details&quot;]/div[@class=&quot;inventory_details_container&quot;]/div[@class=&quot;inventory_details_img_container&quot;]/img[@class=&quot;inventory_details_img&quot;]</value>
      <webElementGuid>10243819-f5a8-4ec6-b795-f8817f477a58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      <webElementGuid>17b1d28d-0537-4f8f-b983-96267bb60e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Fleece Jacket']</value>
      <webElementGuid>04eb6180-0d99-4d43-8d1a-dc97413d0863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>78d11345-bdd4-42d6-8033-81c84e1a8173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Fleece Jacket' and @src = '/static/media/sauce-pullover-1200x1500.51d7ffaf301e698772c8.jpg']</value>
      <webElementGuid>3c457d3c-1b41-41b7-9854-6e20971c5b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
